// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_Katiew8.Models;

namespace Mission6_Katiew8.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230222041757_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_Katiew8.Models.CategoryTable", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Category = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            Category = "Adventure"
                        },
                        new
                        {
                            CategoryId = 3,
                            Category = "Comedy"
                        },
                        new
                        {
                            CategoryId = 4,
                            Category = "Drama"
                        },
                        new
                        {
                            CategoryId = 5,
                            Category = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 6,
                            Category = "Horror"
                        },
                        new
                        {
                            CategoryId = 7,
                            Category = "Musical"
                        },
                        new
                        {
                            CategoryId = 8,
                            Category = "Mystery"
                        },
                        new
                        {
                            CategoryId = 9,
                            Category = "Romance"
                        },
                        new
                        {
                            CategoryId = 10,
                            Category = "Rom-Com"
                        },
                        new
                        {
                            CategoryId = 11,
                            Category = "Science Fiction"
                        },
                        new
                        {
                            CategoryId = 12,
                            Category = "Sports"
                        },
                        new
                        {
                            CategoryId = 13,
                            Category = "Thriller"
                        },
                        new
                        {
                            CategoryId = 14,
                            Category = "Western"
                        });
                });

            modelBuilder.Entity("Mission6_Katiew8.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1,
                            Director = "Ridley Scott",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "R",
                            Title = "Gladiator",
                            Year = 2000
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 3,
                            Director = "Christopher Guest",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Best in Show",
                            Year = 2000
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 3,
                            Director = "Savage Steve Holland",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "Better Off Dead",
                            Year = 1985
                        });
                });

            modelBuilder.Entity("Mission6_Katiew8.Models.MovieResponse", b =>
                {
                    b.HasOne("Mission6_Katiew8.Models.CategoryTable", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
